### ISSUE TITLE
Error when cap deploy

### ISSUE THREAD

**Issue by ymarzack** [sshingler/capistrano-resque#53]
Hello! 

On Mac osx, rvm. Rails 3.2.12, ruby 1.9.3, i've always this error when i try to use cap task :

```
/Users/xxx/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/variables.rb:122:in `method_missing_with_variables': undefined method `_cset' for #<Capistrano::Configuration:0x007f995390ef40> (NoMethodError)
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-resque-0.1.0/lib/capistrano-resque/capistrano_integration.rb:9:in `block in load_into'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:97:in `instance_eval'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:97:in `load'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:83:in `load'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-resque-0.1.0/lib/capistrano-resque/capistrano_integration.rb:7:in `load_into'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-resque-0.1.0/lib/capistrano-resque/capistrano_integration.rb:126:in `<top (required)>'
    from /Users/yzack/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/yzack/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-resque-0.1.0/lib/capistrano-resque.rb:2:in `<top (required)>'
    from /Users/yzack/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
    from /Users/yzack/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
    from /Users/yzack/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:152:in `require'
    from Capfile:4:in `load'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:93:in `instance_eval'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:93:in `load'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:172:in `load_from_file'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:89:in `load'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:86:in `block in load'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:86:in `each'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/configuration/loading.rb:86:in `load'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:65:in `block in load_recipes'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:65:in `each'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:65:in `load_recipes'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:31:in `execute!'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:14:in `execute'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/gems/capistrano-2.14.2/bin/cap:4:in `<top (required)>'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/bin/cap:19:in `load'
    from /Users/yzack/.rvm/gems/ruby-1.9.3-p194@fnordmetric/bin/cap:19:in `<main>'
```

Everything working well without capistrano-resque gem
See it ?

**Comment by gutomcosta** [comment]
Hello, I'm with the same problem here. I'm using Capistrano 3.5 and the problem persists. What do you mean about an old configuration file? 
I need to include some requires in my cap file?
